repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/facebook/usort
    rev: v1.0.7
    hooks:
      - id: usort

  - repo: https://github.com/jsh9/pydoclint
    rev: 81704368e3368c4f7b6d6ea6b16b163608579d65
    hooks:
      - id: pydoclint
        args: [--config=pyproject.toml]
