repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: ./.conda/bin/pytest tests
      language: system
      types: [python]
      pass_filenames: false
      always_run: true
