repos:
  - repo: local
    hooks:
    - id: ruff format & sort imports
      name: ruff format & sort imports
      entry: bash -c 'ruff check --select I --fix && ruff format'
      language: system
      types: [python]
      pass_filenames: false

  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: ./.conda/bin/pytest tests
      language: system
      types: [python]
      pass_filenames: false
      always_run: true
