model:
  type: classifier
  params:
    model_name: HuggingFaceTB/SmolLM-135M 

dataset:
  type: q_timelines
  params:
    augment: true

trainer:
  type: sft
  params:
    lr: 1e-2
    batch_size: 32
    gradient_accumulation_steps: 16
    n_epochs: 30
    use_wandb: true
    push_to_hub: true
    hf_dir: classifier_smoll_135m_a
    balance_classes: false
    patience: null
