model:
  type: classifier
  params:
    model_name: bert-base-uncased

dataset:
  type: q_timelines
  params:
    augment: false
trainer:
  type: sft
  params:
    lr: 1e-3
    batch_size: 16
    n_epochs: 5
    use_wandb: true
    push_to_hub: true
    hf_dir: classifier_bert
    patience: 10
    balance_classes: false
