model:
  type: classifier
  params:
    model_name: meta-llama/Llama-3.2-3B-Instruct

dataset:
  type: q_timelines
  params:
    augment: false

trainer:
  type: sft
  params:
    lr: 1e-4
    batch_size: 64
    max_gpu_batch_size: 4
    n_epochs: 20
    use_wandb: true
    push_to_hub: true
    hf_dir: classifier_llama_3b
    balance_classes: false
    patience: 10

