model:
  type: classifier
  params:
    model_name: meta-llama/Llama-3.2-3B-Instruct

dataset:
  type: q_timelines
  params: {}

trainer:
  type: sft
  params:
    lr: 1e-3
    batch_size: 8
    n_epochs: 20
    output_path: classifier/meta-llama/weights_balanced.pt
    use_wandb: true
    push_to_hub: true
    hf_dir: classifier_llama_3b_balanced
    balance_classes: true
    patience: 3

