model:
  type: classifier
  params:
    model_name: HuggingFaceTB/SmolLM-135M 

dataset:
  type: levels
  params:
    augment: false
    level: 2

trainer:
  type: sft
  params:
    lr: 1e-3
    batch_size: 64
    gradient_accumulation_steps: 8
    n_epochs: 30
    use_wandb: true
    push_to_hub: true
    hf_dir: smoll_135m_levels
    balance_classes: false
    patience: null
