model:
  type: classifier
  params:
    model_name: meta-llama/Llama-3.2-1B-Instruct

dataset:
  type: q_timelines
  params: {}

trainer:
  type: sft
  params:
    lr: 1e-3
    batch_size: 2
    n_epochs: 5
    output_path: classifier/meta-llama/weights.pt
    use_wandb: true
