model:
  type: classifier
  params:
    model_name: google-bert/bert-base-uncased

dataset:
  type: q_timelines
  params: {}

trainer:
  type: sft
  params:
    lr: 1e-3
    batch_size: 128
    n_epochs: 10
    output_path: classifier
