model:
    model_name_or_path: HuggingFaceTB/SmolLM2-135M
    trust_remote_code: True

data:
    dataset_name: matres
    train_split: train
    valid_split: valid
    max_seq_length: 4096
    augment: False
    pad_to_max_length: False # To pad each batch at runtime
    shuffle_train_dataset: True
    shuffle_seed: 42

trainer:
    output_dir: models/smol-135-tq
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 64
    num_train_epochs: 30
    learning_rate: 5e-4
    max_grad_norm: 1.0
    load_best_model_at_end: True
    seed: 42
    bf16: True
    push_to_hub: True
    hub_model_id: hugosousa/smol-135-tq
    label_smoothing_factor: 0.01
    torch_compile: False
    early_stopping_patience: 3
    init_bias: True
    lr_scheduler:
        warmup_factor: 0.001
        warmup_steps_pct: 0.02
        factor: 0.1
        patience: 2
    freeze_backbone: True
