model:
    model_name_or_path: HuggingFaceTB/SmolLM2-135M
    trust_remote_code: True
    n_score_hidden_layers: 2

data:
    dataset_name: point_tempeval
    train_split: train
    valid_split: valid
    max_seq_length: 4096
    augment: False
    closure: False
    synthetic: True
    pad_to_max_length: False # To pad each batch at runtime
    shuffle_train_dataset: True
    shuffle_seed: 42

trainer:
    output_dir: models/smol-135-s
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    max_batch_size_per_device: 16
    num_train_epochs: 10
    learning_rate: 3e-4
    max_grad_norm: 0.5
    load_best_model_at_end: True
    seed: 42
    bf16: True
    push_to_hub: True
    hub_model_id: hugosousa/smol-135-s
    label_smoothing_factor: 0.03
    torch_compile: False
    early_stopping_patience: 5
    init_bias: True
    lr_scheduler:
        warmup_factor: 0.001
        warmup_steps_pct: 0.02
    freeze_backbone: False
    hp_search: True
